export enum destinationActions {
  CATCH_ERROR = 'DESTINATION/CATCH_ERROR',
  TOGGLE_LOADING = 'DESTINATION/TOGGLE_LOADING',
  LOAD_DESTINATION_LIST = 'DESTINATION/LOAD_DESTINATION_LIST',
  LOAD_DESTINATION_ITEM = 'DESTINATION/LOAD_DESTINATION_ITEM',
  SET_DESTINATION_ITEM = 'DESTINATION/SET_DESTINATION_ITEM',
  SET_DESTINATION_LIST = 'DESTINATION/SET_DESTINATION_LIST'
}
