export enum ticketActions {
  SET_TICKET_LIST = 'TICKET/GET_TICKET_LIST',
  GET_USER_TICKETS = 'TICKET/GET_USER_TICKETS',
  GET_USER_TICKET = 'TICKET/GET_USER_TICKET',
  LOAD_TICKET_LIST = 'TICKET/LOAD_TICKET_LIST',
  GET_TICKET_BY_ID = 'TICKET/GET_TICKET_BY_ID',
  CATCH_ERROR = 'TICKET/CATCH_ERROR',
  TOGGLE_LOADING = 'TICKET/TOGGLE_LOADING',
  CREATE_TICKETS = 'TICKET/CREATE_TICKETS'
}
