export enum userActions {
  SET_USER_PROFILE = 'USER/SET_USER_PROFILE',
  SET_USER_TICKETS = 'USER/SET_USER_TICKETS',
  SET_TEMPORARY_CHOSEN_DESTINATION = 'USER/SET_TEMPORARY_CHOSEN_DESTINATION',
  LOGIN = 'USER/LOGIN',
  REGISTER = 'USER/REGISTER',
  TOGGLE_LOADING = 'USER/TOGGLE_LOADING',
  CATCH_ERROR = 'USER/CATCH_ERROR',
  LOGOUT = 'USER/LOGOUT',
  UPDATE = 'USER/UPDATE'
}
