stages:
  - test

test-linters:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  image: node:12-slim
  script: 
    - "npm install && npm run test:linters"
  only:
    - merge_requests